local constants = {
    TILE_SIZE = 64.0,
    LISTEN_POWER_UPDATE = "LISTEN_POWER_UPDATE",
    LISTEN_POWER_OUTAGE = "LISTEN_POWER_OUTAGE",
    POWER_UPDATE = "POWER_UPDATE",
    POWER_OUTAGE = "POWER_OUTAGE",
    LISTEN_PLAYER_COLLISION = "LISTEN_PLAYER_COLLISION",
    PLAYER_COLLISION = "PLAYER_COLLISION"
}

return constants
