local constants = {
    TILE_SIZE = 64.0,
    LISTEN_POWER_UPDATE = "LISTEN_POWER_UPDATE",
    LISTEN_POWER_OUTAGE = "LISTEN_POWER_OUTAGE",
    POWER_UPDATE = "POWER_UPDATE",
    POWER_OUTAGE = "POWER_OUTAGE",
    LISTEN_PLAYER_SIPHON_ENTER = "LISTEN_PLAYER_SIPHON_ENTER",
    PLAYER_SIPHON_ENTER = "PLAYER_SIPHON_ENTER",
    LISTEN_PLAYER_SIPHON_EXIT = "LISTEN_PLAYER_SIPHON_EXIT",
    PLAYER_SIPHON_EXIT = "PLAYER_SIPHON_EXIT",
    LISTEN_ROBOT_COLLISION = "LISTEN_ROBOT_COLLISION",
    ROBOT_COLLISION = "ROBOT_COLLISION",
    LISTEN_FIRE_PRESS = "LISTEN_FIRE_PRESS",
    FIRE_PRESS = "FIRE_PRESS",
    FIRE_RELEASE = "FIRE_RELEASE"
}

return constants
