local constants = require "constants"

function init(self)
    msg.post(".", "acquire_input_focus")

end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	local start_clicked = action_id == hash(constants.CLICK) and gui.pick_node(gui.get_node("start"), action.x, action.y)
	if (start_clicked or action_id == hash(constants.SPACE)) and action.pressed then
		msg.post("controller:/controller", constants.START_GAME)
	end
end