local camera = require "orthographic.camera"

function init(self)
	msg.post("control", "REQUEST_CONTROL")
	self.camera_id = go.get_id("/camera")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("NEW_POSITION") then
		local screen = vmath.vector3(message.x, message.y, 0)
		local world = camera.screen_to_world(self.camera_id, screen)
		local pos = go.get_position()
		local z = pos.z
		go.set_position(vmath.vector3(world.x, world.y, z))
	end
end